---

# vim: sw=2 ts=2 et

- hosts: all
  tasks:
  - name: Install necessary test dependencies for Fedora
    dnf:
      state: present
      name:
        - coreutils
        - perl-IPC-SysV
        - perl-Time-HiRes
        - rpm-build
        - systemd
        - systemd-container
        - util-linux

